/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PBNCovertFrame.java
 *
 * Created on Mar 12, 2012, 10:14:42 PM
 */

package paintbynumberpro;

/**
 *
 * @author user
 */
public class PBNCovertFrame extends javax.swing.JFrame {

    private ProgressBarComponent myProgressBar;

    /** Creates new form PBNCovertFrame */
    public PBNCovertFrame(PBNPuzzle thePuzzle) {
        initComponents();
        myProgressBar.setPuzzle (thePuzzle);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Stop_JButton = new javax.swing.JButton();
        ProgressBar_JPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Stop_JButton.setText("Stop");

        org.jdesktop.layout.GroupLayout ProgressBar_JPanelLayout = new org.jdesktop.layout.GroupLayout(ProgressBar_JPanel);
        ProgressBar_JPanel.setLayout(ProgressBar_JPanelLayout);
        ProgressBar_JPanelLayout.setHorizontalGroup(
            ProgressBar_JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 360, Short.MAX_VALUE)
        );
        ProgressBar_JPanelLayout.setVerticalGroup(
            ProgressBar_JPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 65, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(ProgressBar_JPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, Stop_JButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(ProgressBar_JPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Stop_JButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        myProgressBar = new ProgressBarComponent();
        ProgressBar_JPanel.add(myProgressBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProgressBar_JPanel;
    private javax.swing.JButton Stop_JButton;
    // End of variables declaration//GEN-END:variables

}
